# Generated by Django 2.0.6 on 2018-06-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Icon')),
                ('contact_url', models.URLField(max_length=1024)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='App Name')),
                ('icon_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Icon')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsistanbul_job.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=512)),
                ('city', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsistanbul_job.Company')),
            ],
        ),
    ]
