# Generated by Django 2.0.6 on 2018-07-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsistanbul_job', '0002_auto_20180614_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyapp',
            options={'verbose_name': 'Company App', 'verbose_name_plural': 'Company Apps'},
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_url',
            field=models.URLField(max_length=1024, verbose_name='Contact URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='icon_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='companyapp',
            name='icon_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL'),
        ),
    ]
