# Generated by Django 2.0.6 on 2018-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsistanbul_job', '0003_auto_20180702_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_url',
            field=models.CharField(max_length=2048, verbose_name='Contact URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='icon_url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='companyapp',
            name='icon_url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='Company Name', max_length=256, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL'),
        ),
    ]
