# Generated by Django 2.0.6 on 2018-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsistanbul_job', '0004_auto_20180708_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('avatar_url', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Avatar URL')),
                ('external_url', models.CharField(blank=True, max_length=2048, null=True, verbose_name='External URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyapp',
            options={'ordering': ('name',), 'verbose_name': 'Company App', 'verbose_name_plural': 'Company Apps'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('position_title',)},
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=256, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='about',
            name='contributor',
            field=models.ManyToManyField(to='nsistanbul_job.Contributor'),
        ),
    ]
